default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :beta do
    upload_to_testflight(
      ipa: "/tmp/TherapyFlowExport/TherapyFlow.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
